IF EXISTS (SELECT TOP 1 1 FROM SYS.DATABASES WHERE NAME='RECRUITERSDAIRY')
DROP DATABASE RECRUITERSDAIRY

CREATE DATABASE RECRUITERSDAIRY
USE RECRUITERSDAIRY
GO

IF OBJECT_ID('JOB')IS NOT NULL  DROP TABLE JOB
CREATE TABLE JOB
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[JOBID] INT,
[DESCRIPTION] VARCHAR (50),
)

IF OBJECT_ID('CANDIDATE')IS NOT NULL  DROP TABLE CANDIDATE
CREATE TABLE CANDIDATE
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[NAME] VARCHAR (40) NOT NULL,
[ADDRESS] VARCHAR (100) NOT NULL,
[PHONE] INT  NOT NULL,
[EMAIL] VARCHAR (100) NOT NULL,
[NOTES] VARCHAR (1000) NOT NULL,
[JOBNUMBER] INT NOT NULL,FOREIGN KEY(ID) REFERENCES JOB(ID),
)


