IF EXISTS (SELECT TOP 1 1 FROM SYS.DATABASES WHERE NAME='RECRUITERSDAIRY')
DROP DATABASE RECRUITERSDAIRY

CREATE DATABASE RECRUITERSDAIRY
USE RECRUITERSDAIRY
GO

IF OBJECT_ID('JOB')IS NOT NULL  DROP TABLE JOB
CREATE TABLE JOB
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[TITLE]  VARCHAR (100) NOT NULL,
[DESCRIPTION] VARCHAR (500) NOT NULL,
[REQUIREMENTS] VARCHAR (1000),
[LOCATION] VARCHAR(500) NOT NULL,
[PAYRANGE1] VARCHAR(300) NOT NULL,
[PAYRANGE2] VARCHAR(300) NOT NULL,
[CONTACTPER] VARCHAR(200) NOT NULL,
[CONTACTPHONE] INT NOT NULL,
)

IF OBJECT_ID('CANDIDATE')IS NOT NULL  DROP TABLE CANDIDATE
CREATE TABLE CANDIDATE
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[NAME] VARCHAR (300) NOT NULL,
[ADDRESS] VARCHAR (1000) NOT NULL,
[PHONE] INT  NOT NULL,
[EMAIL] VARCHAR (400) NOT NULL,
[NOTES] VARCHAR (3000) NOT NULL,
[SUBMISSIONSTATUS] VARCHAR(300),
[JOBID] INT NOT NULL,FOREIGN KEY(JOBID) REFERENCES JOB(ID),
)
IF OBJECT_ID('ROLES')IS NOT NULL  DROP TABLE ROLES
CREATE TABLE ROLES
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[ROLEID] INT NOT NULL UNIQUE ,
[DESCRIPTION] VARCHAR (400) NOT NULL,

)

IF OBJECT_ID('USERS')IS NOT NULL  DROP TABLE USERS
CREATE TABLE USERS
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[EMAIL] VARCHAR (100) NOT NULL,
[PASSWORD] VARCHAR (200) NOT NULL,
[ROLEID] INT NOT NULL REFERENCES ROLES(ROLEID),
)

IF OBJECT_ID('TEAMMEMBERS')IS NOT NULL  DROP TABLE TEAMMEMBERS
CREATE TABLE TEAMMEMBERS
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[USERID] INT NOT NULL REFERENCES USERS(ID),
[TEAMMEMBERS] VARCHAR (1000) NOT NULL, 
)

