IF EXISTS (SELECT TOP 1 1 FROM SYS.DATABASES WHERE NAME='RECRUITERSDAIRY')
DROP DATABASE RECRUITERSDAIRY

CREATE DATABASE RECRUITERSDAIRY
USE RECRUITERSDAIRY
GO

IF OBJECT_ID('JOB')IS NOT NULL  DROP TABLE JOB
CREATE TABLE JOB
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[JOBID1] INT NOT NULL,
[JOBDESCRIPTION] VARCHAR (50) NOT NULL,
[JOBREQUIREMENTS] VARCHAR (100),
[JOBLOCATION] VARCHAR(100) NOT NULL,
[JOBPAYRANGE1] VARCHAR(100) NOT NULL,
[JOBPAYRANGE2] VARCHAR(100) NOT NULL,
[JOBCONTACTPER] VARCHAR(100) NOT NULL,
[JOBCONTACTPHONE] INT NOT NULL,
)

IF OBJECT_ID('CANDIDATE')IS NOT NULL  DROP TABLE CANDIDATE
CREATE TABLE CANDIDATE
(
[ID] INT PRIMARY KEY IDENTITY(1,1),
[NAME] VARCHAR (40) NOT NULL,
[ADDRESS] VARCHAR (100) NOT NULL,
[PHONE] INT  NOT NULL,
[EMAIL] VARCHAR (100) NOT NULL,
[NOTES] VARCHAR (1000) NOT NULL,
[SUBMISSIONSTATUS] VARCHAR(200),
[JOBNUMBER] INT NOT NULL,FOREIGN KEY(ID) REFERENCES JOB(ID),
)


